= antora-extensions-and-testing

This repository is used for developing Antora extensions and testing them out.

== Prerequisites

. Ensure you have link:https://www.docker.com/get-docker[Docker] installed locally.
. Clone this repository.

== Testing out your Antora extensions

This tool set uses Docker Compose to spin up the following services:

* 'antora' - using the `gilesgas/antora-with-inotify-tools-and-lunr-integration` Docker image, and
* 'web' (using `httpd:alpine`) - to display the static web content generated by the antora service.

To begin this simple process:

. `cd` into your locally cloned `antora-extensions-and-testing` directory.

. Run the Docker command `docker-compose up`.

. Open your web browser to `http://localhost:10000`.
+
Whenever you edit content within the `modules/ROOT` directory and save it - e.g. any `.adoc` file within this directory structure, refresh the relevant web page and you'll see the content updated!

+
You should also be able to edit your Antora extensions in the `/lib` directory to see these in action too.

NOTE: The `remote-include-processor.js` extension won't work until you add `curl` to the Docker image (above).
